fix(validation): implement validation for  sign up
atlp-rwanda/eagles-ec-be pull request #20
Opened 2024-04-20 12:15 UTC by yvanddniyo

**What does this PR do?**
This pull request implement  user validation for the sign up features and deny the extra fields for existing user fields.  User must provide valid email when a user provide invalid email the middleware deny it and return error. And also name of user can be lower than 5 characters as same as username can not go below 4  characters.

**Description of Task to be completed?**
Here are the endpoint working:

GET /api/v1/users
POST /api/v1/users/register

**How should this be manually tested?**

Clone the repository.
Checkout to the branch fix-userSignup-Validation#187431242.
Run npm install to install dependencies.
Run npm run dev to start the development server.
Open your postman or other your testing app and run http://localhost:3000/api/v1/users this allow you to retrieve existing user within in the database.
Use the endpoint of http://localhost:3000/api/v1/users/register to register a user using name, username, email and password.

**What are the relevant pivotal tracker stories?**

#187431242

**Screenshot**

![Screenshot (2)](https://github.com/atlp-rwanda/eagles-ec-be/assets/105001832/af67f689-7ddb-410f-80cf-9d25d0489da6)
![Screenshot (3)](https://github.com/atlp-rwanda/eagles-ec-be/assets/105001832/c6100c4a-d67c-4f79-8f51-151d67ea33f4)
![Screenshot (4)](https://github.com/atlp-rwanda/eagles-ec-be/assets/105001832/2b4ec8c5-54da-46b5-b508-22ee1498badb)

2024-04-22 16:59 UTC, teerenzo requested changes

2024-04-22 16:59 UTC, teerenzo commented on src/controllers/userControllers.ts
> +    }
make this helper function to be able to reuse it

2024-04-23 08:27 UTC, teerenzo requested changes

2024-04-23 08:27 UTC, teerenzo commented on src/routes/userRoutes.ts
> + validateUserSignUp,
not like this @yvanddniyo this function will accept schema as parameter like this `validateSchema(signUpSchema)`

2024-04-23 09:06 UTC, teerenzo requested changes

2024-04-23 09:06 UTC, teerenzo commented on src/validation/validate.ts
> +export default signUpSchema
the folder should be something like schemas and also the file should be signUpSchema

2024-04-23 09:06 UTC, teerenzo commented on src/validation/validate.ts
> +export default signUpSchema
the folder should be something like schemas and also the file should be signUpSchema

2024-04-23 11:34 UTC, Jovz19200 approved these changes
Well Done Yvan!

2024-04-23 12:03 UTC, Heisjabo approved these changes

2024-04-23 13:56 UTC, soleil00 approved these changes
except creating unneccessary schema your fix work as intended, u may consider to refactor ur code in near the future😌

2024-04-23 13:56 UTC, soleil00 commented on src/schemas/signUpSchema.ts
creating schema folder is unneccessary, u should define your schem inside validator middleware and use it inside,

2024-04-24 13:54 UTC, teerenzo approved these changes

2024-04-24 13:54 UTC, merged