#187419169 user can login via email and password
atlp-rwanda/eagles-ec-be pull request #24
Opened 2024-04-22 20:43 UTC by niyobertin

**What does this PR do?**

Validation of user login data

**Description of Task to be completed?**

The user data from request.body are validated using Joi

**How should this be manually tested?**

Clone this repository , cd into it and run:

npm run dev to start server . while server running, use postman and send
1.POST request on locahost:PORT/api/v1/users/login by providing email and password.
it will return jwt as result of successful login.
in case of failure it will return error based on failing field.

**What are the relevant pivotal tracker/Trello stories?**

[#187419169](https://www.pivotaltracker.com/n/projects/2701065)

2024-04-23 07:46 UTC, teerenzo commented
squash your commits to be one commit

2024-04-23 08:24 UTC, teerenzo requested changes

2024-04-23 08:24 UTC, teerenzo commented on src/moddewares/joiValifdation.ts
> +}
remove this if you are not using it

2024-04-23 12:42 UTC, Jovz19200 approved these changes
Awesome !!!

2024-04-23 14:36 UTC, soleil00 approved these changes
despit comment ur fix wor as expected , u too u may consider refacto in near the future

2024-04-23 14:36 UTC, soleil00 commented on src/helpers/validation.ts
> +        return res.status(406).json({
wrong status u should use 400 here 406 is used for unacceptable which is related to content type but u used it for field validations

2024-04-23 14:36 UTC, soleil00 commented on src/middlewares/joiValidation.ts
creating joiValidation in helper and creating validation in middleware on my point of view its unnecessary u can either create middleware that handle both loginValidation schema u can move it into validation in middleware or mode down validation in middleware into helper

2024-04-29 12:21 UTC, teerenzo requested changes

2024-04-29 12:21 UTC, teerenzo commented on __test__/user.test.ts
> -
why did you remove this

2024-04-29 13:43 UTC, teerenzo commented
I can't see where you have validated your fields on login @niyobertin please pay attention to details and test before raising any PR

2024-04-29 13:43 UTC, teerenzo requested changes

2024-04-29 13:43 UTC, teerenzo commented on src/routes/userRoutes.ts
>  import { passwordUpdateSchema } from "../schemas/passwordUpdate";
where is validation of login

2024-04-29 15:56 UTC, teerenzo requested changes

2024-04-29 15:56 UTC, teerenzo commented on src/routes/userRoutes.ts
>  userRoutes.post("/register", emailValidation, validateSchema(signUpSchema), createUserController);
what about email

2024-04-29 19:27 UTC, closed without merging