Ft account activation #187419176
atlp-rwanda/eagles-ec-be pull request #44
Opened 2024-05-04 11:54 UTC by MugemaneBertin2001

# what does this PR do?
- Enables an admin to activate and deactivate user account 
# description of task to be complete
- Due to varying reasons e.g fraud, abuse, malicious use or violation of terms of service, admin should be able to diable any user account.

- An admin should be able to activate / reactive an account.
for deactivation, send an email to the user with reasons for deactivation

## How should this be manually tested?
1. checkout this branch and run app
2. create a user
3.  patch /api/v1/users/{userId}/status
![Screenshot 2024-05-04 135338](https://github.com/atlp-rwanda/eagles-ec-be/assets/59690243/cf385d40-299b-491b-9e95-0764a1e4b7eb)
![Screenshot 2024-05-04 135147](https://github.com/atlp-rwanda/eagles-ec-be/assets/59690243/b92dd101-eba0-4524-9b85-b263c6a350b4)

# pivotal tracker id ---->#187419176

2024-05-04 15:53 UTC, teerenzo requested changes

2024-05-04 15:53 UTC, teerenzo commented on .vscode/settings.json
> +}
remove this

2024-05-04 15:53 UTC, teerenzo commented on src/services/user.service.ts
> +    console.error('Error updating user account status:', error.message);
remove this console

2024-05-04 15:53 UTC, teerenzo commented on src/services/user.service.ts
> +    console.error('Error updating user account status:', error.message);
remove this console

2024-05-04 20:42 UTC, Heisjabo approved these changes

2024-05-04 20:52 UTC, soleil00 approved these changes

2024-05-04 20:59 UTC, yvanddniyo approved these changes
look good but Make sure you squash your commit.

2024-05-06 15:51 UTC, teerenzo requested changes

2024-05-06 15:51 UTC, teerenzo commented on .vscode/settings.json
> +}
remove it

2024-05-06 15:51 UTC, teerenzo commented on src/services/user.service.ts
> +      }
this is not server , return other message with different status code

2024-05-07 10:28 UTC, teerenzo approved these changes

2024-05-07 10:28 UTC, merged