#187419198 User should interact with each others via chats publicly
atlp-rwanda/eagles-ec-be pull request #48
Opened 2024-05-09 08:32 UTC by niyobertin

**What does this PR do?**

Have chats room to interact  with each other to ask information publicly.
**Description of Task to be completed?**

Have the following end point 
GET: /api/v1/messages
**How should this be manually tested?**
After cloning the repo, cd into it and run _npm run dev_  to start the server.

- using your browser vist http://localhost:PORT/api/v1/messages you will be provided by the link to join the chat room.
- provide your username and text your message the send.

**Any background context you want to provide?**
when a user send a message it will be echoed to all online users

**What are the relevant pivotal tracker stories?**

[Delivers #[187419198](https://www.pivotaltracker.com/n/projects/2701065)]

2024-05-09 08:48 UTC, teerenzo requested changes

2024-05-09 08:48 UTC, teerenzo commented on src/routes/chatRoutes.ts
> +export default chatRoutes;
you don't need to have this as route just have config of your socket, if you decide to this without route remove this and have it as config of socket

2024-05-09 08:48 UTC, teerenzo commented on src/utils/server.ts
> +
this not route have socket as config and you call it here

2024-05-15 08:42 UTC, yvanddniyo approved these changes
LGTM

2024-05-15 08:42 UTC, MugemaneBertin2001 approved these changes
LGTM

2024-05-15 10:08 UTC, teerenzo approved these changes

2024-05-15 10:08 UTC, teerenzo approved these changes

2024-05-15 16:37 UTC, merged