Reset Password via email #187419172
atlp-rwanda/eagles-ec-be pull request #58
Opened 2024-05-16 17:34 UTC by MugemaneBertin2001

# What does this PR do?
- Password reset functionality is missing in our application. Its' invaluable in instances where our users forget their login credentials.
# Task completed
- Send password reset in via email
- create new password
- send confirmation emails
# how totest this feature
- clone this `repo`
- set up local configuration
- browse to `localhost:499/docs
![Screenshot 2024-05-16 192926](https://github.com/atlp-rwanda/eagles-ec-be/assets/59690243/46a1007d-b586-4b7a-a425-b921f04f313d)

![Screenshot 2024-05-16 192904](https://github.com/atlp-rwanda/eagles-ec-be/assets/59690243/cc6ef264-ddcc-4275-a04f-b130337a5752)

Feat: Reset Password via email#187419172

2024-05-17 16:30 UTC, teerenzo requested changes

2024-05-17 16:30 UTC, teerenzo commented on src/email-templates/generatePasswordUpdateEmailContent.ts
> + */
remove this

2024-05-18 12:51 UTC, Heisjabo approved these changes

2024-05-18 14:16 UTC, Jovz19200 approved these changes
Good Job!!

2024-05-18 17:15 UTC, teerenzo approved these changes

2024-05-18 17:16 UTC, merged