ft(reviews): implement product reviews
atlp-rwanda/eagles-ec-be pull request #61
Opened 2024-05-17 16:11 UTC by yvanddniyo

**What does this PR do?**

This PR allow buyer who  successfully bought the product to provide review of it.

**Description of Task to be completed?**

User should be a buyer to review the products
User should be successfully  bought the products.

**How should this be manually tested?**

Clone the repository.
Checkout to the branch ft-product-review-#187419185
Run npm install to install dependencies.
Run npm run migrate and npm run seed
Run npm run dev to start the development server.
Open a web browser and navigate to the /docs endpoint (e.g., http://localhost:PORT/docs).
Verify that the Swagger UI loads correctly.
First authorize by logging in any user and use the token provided.
Explore the endpoints for reviews and verify that everything is working.

**What are the relevant pivotal tracker stories?**

[Deliveries #187419185]

2024-05-20 16:51 UTC, MugemaneBertin2001 approved these changes
LGTM

2024-05-20 16:59 UTC, Heisjabo approved these changes

2024-05-21 03:29 UTC, Jovz19200 approved these changes
Good work done there!!

2024-05-21 09:44 UTC, teerenzo commented
PR title is wrong

2024-05-21 12:43 UTC, teerenzo requested changes

2024-05-21 12:43 UTC, teerenzo commented on src/sequelize/migrations/20240515125226-reviews.js
> +    },
references?

2024-05-21 12:43 UTC, teerenzo commented on src/sequelize/models/reviews.ts
> +    },
references?

2024-05-21 14:39 UTC, teerenzo approved these changes

2024-05-21 15:00 UTC, merged