fix: Creating a user profile on user sign up with google
atlp-rwanda/eagles-ec-be pull request #88
Opened 2024-07-04 21:37 UTC by niyobertin

#### What does this PR do?
When a user sign in with google, create user profile

#### Description of Task to be completed?

- login with google 
- update last password update time when a user rest his/ her password

#### How should this be manually tested?
Clone this rep, cd into it, checkout this branch _fix-user-profile_ 

- run npm  dev to start the server then sign  in with google. 
- After successfull sign in, view your profile

2024-07-04 21:49 UTC, teerenzo requested changes

2024-07-04 21:49 UTC, teerenzo commented on src/controllers/userControllers.ts
> +       });
this is not what we talked

2024-07-05 12:54 UTC, Heisjabo approved these changes

2024-07-05 14:25 UTC, teerenzo approved these changes

2024-07-05 14:25 UTC, merged